// glTF 2.0 / GLB writer for the project's geometry-only assets.
// Retains editable mesh data, materials, hierarchy, node names and TRS transforms.
import {mkdir,writeFile} from 'node:fs/promises';
import {createAnimal,createVehicle} from '../dist/src/models.js';
import {createCreature,CREATURE_MODELS} from '../dist/src/creatures.js';
function exportGLB(root){
 const json={asset:{version:'2.0',generator:'TankRush original low-poly asset pipeline',copyright:'Jan van Wassenhove / mITy.John'},scene:0,scenes:[{nodes:[0]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}]};
 const chunks=[],materialMap=new Map();let byteOffset=0;
 function accessor(attribute,target){const array=attribute.array,data=Buffer.from(array.buffer,array.byteOffset,array.byteLength),padding=(4-data.length%4)%4,view=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset,byteLength:data.length,target});chunks.push(data,Buffer.alloc(padding));byteOffset+=data.length+padding;const componentType=array instanceof Float32Array?5126:array instanceof Uint32Array?5125:array instanceof Uint16Array?5123:5121;const a={bufferView:view,componentType,count:attribute.count,type:({1:'SCALAR',2:'VEC2',3:'VEC3',4:'VEC4'})[attribute.itemSize]};if(attribute.itemSize===3){a.min=[Infinity,Infinity,Infinity];a.max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<attribute.count;i++)for(let k=0;k<3;k++){const v=array[i*3+k];a.min[k]=Math.min(a.min[k],v);a.max[k]=Math.max(a.max[k],v);}}json.accessors.push(a);return json.accessors.length-1;}
 function getMaterial(m){const spec={name:m.name||'surface',pbrMetallicRoughness:{baseColorFactor:[m.color.r,m.color.g,m.color.b,m.opacity],metallicFactor:m.metalness??0,roughnessFactor:m.roughness??.6},doubleSided:m.side===2};if(m.emissive)spec.emissiveFactor=m.emissive.toArray().map(c=>Math.min(1,c*(m.emissiveIntensity??1)));if(m.transparent)spec.alphaMode='BLEND';const key=JSON.stringify(spec);if(materialMap.has(key))return materialMap.get(key);const id=json.materials.push(spec)-1;materialMap.set(key,id);return id;}
 function visit(o){const id=json.nodes.length,node={name:o.name||o.type,translation:o.position.toArray(),rotation:o.quaternion.toArray(),scale:o.scale.toArray()};json.nodes.push(node);if(o.isMesh){const geo=o.geometry,attributes={};for(const [name,semantic] of [['position','POSITION'],['normal','NORMAL'],['uv','TEXCOORD_0']])if(geo.attributes[name])attributes[semantic]=accessor(geo.attributes[name],34962);const primitive={attributes,material:getMaterial(o.material)};if(geo.index)primitive.indices=accessor(geo.index,34963);node.mesh=json.meshes.push({name:o.name,primitives:[primitive]})-1;}if(o.children.length)node.children=o.children.map(visit);return id;}
 visit(root);json.buffers[0].byteLength=byteOffset;const raw=Buffer.from(JSON.stringify(json)),j=Buffer.concat([raw,Buffer.alloc((4-raw.length%4)%4,32)]),binary=Buffer.concat(chunks);const header=Buffer.alloc(12);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(12+8+j.length+8+binary.length,8);const jh=Buffer.alloc(8),bh=Buffer.alloc(8);jh.writeUInt32LE(j.length,0);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(binary.length,0);bh.writeUInt32LE(0x004e4942,4);return {buffer:Buffer.concat([header,jh,j,bh,binary]),json};
}
await mkdir('dist/models',{recursive:true});const models=[['submarine',createVehicle('aquarium')],['buggy',createVehicle('terrarium')],...['guppy','piranha','spider','snake','monitor','chameleon'].map(type=>[type,createAnimal(type)]),...CREATURE_MODELS.map(type=>[type,createCreature(type)])],manifest=[];
for(const [name,root] of models){const {buffer,json}=exportGLB(root);await writeFile(`dist/models/${name}.glb`,buffer);let triangles=0;root.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});manifest.push({name,file:`${name}.glb`,bytes:buffer.length,triangles,nodes:json.nodes.length,source:CREATURE_MODELS.includes(name)?'../src/creatures.js':'../src/models.js',license:'Original project asset; see ASSETS.md'});console.log(`${name}: ${triangles} triangles, ${(buffer.length/1024).toFixed(0)} KB`);}
await writeFile('dist/models/manifest.json',JSON.stringify(manifest,null,2)+'\n');
